CREATE TABLE DATABASECHANGELOG (
  ID            VARCHAR(63)  NOT NULL,
  AUTHOR        VARCHAR(63)  NOT NULL,
  FILENAME      VARCHAR(200) NOT NULL,
  DATEEXECUTED  datetime     NOT NULL,
  ORDEREXECUTED INT          NOT NULL,
  EXECTYPE      VARCHAR(10)  NOT NULL,
  MD5SUM        VARCHAR(35)  NULL,
  DESCRIPTION   VARCHAR(255) NULL,
  COMMENTS      VARCHAR(255) NULL,
  TAG           VARCHAR(255) NULL,
  LIQUIBASE     VARCHAR(20)  NULL,
  CONSTRAINT PK_DATABASECHANGELOG PRIMARY KEY (ID, AUTHOR, FILENAME(128))
);